// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzlrWv2UHXY3bmjFeXRzIP1eZH9Yt8h-Y',
    appId: '1:1065359764592:web:d3a59ce24a448a42aa58b5',
    messagingSenderId: '1065359764592',
    projectId: 'social-media-app-72cf4',
    authDomain: 'social-media-app-72cf4.firebaseapp.com',
    storageBucket: 'social-media-app-72cf4.firebasestorage.app',
    measurementId: 'G-C1S12PBCG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC26E3NLtrBVkq7Il9HjBF67QJTbzmynu8',
    appId: '1:1065359764592:android:b51a9e0c3c3522e7aa58b5',
    messagingSenderId: '1065359764592',
    projectId: 'social-media-app-72cf4',
    storageBucket: 'social-media-app-72cf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCriRwd-fVdz1ywAqSlJxfMcEuRiCD8_0A',
    appId: '1:1065359764592:ios:f7bc2e9cb3b6feb0aa58b5',
    messagingSenderId: '1065359764592',
    projectId: 'social-media-app-72cf4',
    storageBucket: 'social-media-app-72cf4.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCriRwd-fVdz1ywAqSlJxfMcEuRiCD8_0A',
    appId: '1:1065359764592:ios:f7bc2e9cb3b6feb0aa58b5',
    messagingSenderId: '1065359764592',
    projectId: 'social-media-app-72cf4',
    storageBucket: 'social-media-app-72cf4.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzlrWv2UHXY3bmjFeXRzIP1eZH9Yt8h-Y',
    appId: '1:1065359764592:web:104abed6cc83535caa58b5',
    messagingSenderId: '1065359764592',
    projectId: 'social-media-app-72cf4',
    authDomain: 'social-media-app-72cf4.firebaseapp.com',
    storageBucket: 'social-media-app-72cf4.firebasestorage.app',
    measurementId: 'G-TNVH06JDE2',
  );

}